version: 2
updates:
  # Fetch and update latest `npm` packages
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      time: '00:00'
    rebase-strategy: 'disabled'
    open-pull-requests-limit: 50
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope